<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>_3Garfos.Infra</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="3Garfos.TUnit"  />
        <InternalsVisibleTo Include="3Garfos.xUnit"  />
    </ItemGroup>


</Project>
